### ISSUE TITLE
Finish Registration Page

### ISSUE THREAD

**Issue by jeffreyxchan** [ideahacks/ideahacks.la#20]
**Summary**
Hi! Can you please finish the registration page? That'd be great :)

You didn't have a preference on whether to copy or build from scratch. I would actually prefer if you built it from scratch since it'd be a better learning opportunity for you. I'll also provide the old website code in case you'd like to study off of it, or copy it.

Here's the link to the old website code: https://github.com/jeffreyxchan/IDEA-Hacks-Website  
All the old pages are within the /app/views folder, and all the css and js are within the /public folder at the root of the project.

**Notes**
1. Please use the branch naming convention from last time
2. Please make it look as close to the old registration page as much as possible (ideahacks.la/registration). This is mainly because the registration and the login page should have the same design, and we'll work on redesigning them later (or wait until the design team gives us mockups)

**DUE DATE:** Would **Aug 19** be ok? It's a little more than two weeks, and on a meeting day.

**Comment by sydney-ng** [comment]
Hi Jeffrey, 
I think that August 19th should be OK. I'll keep you updated as I create the page if I need more time or anything :) Sydney  

    On Thursday, August 3, 2017 1:38 AM, Jeffrey Chan <notifications@github.com> wrote:
 

 Summary
Hi! Can you please finish the registration page? That'd be great :)You didn't have a preference on whether to copy or build from scratch. I would actually prefer if you built it from scratch since it'd be a better learning opportunity for you. I'll also provide the old website code in case you'd like to study off of it, or copy it.Here's the link to the old website code: https://github.com/jeffreyxchan/IDEA-Hacks-Website
All the old pages are within the /app/views folder, and all the css and js are within the /public folder at the root of the project.Notes   
   - Please use the branch naming convention from last time
   - Please make it look as close to the old registration page as much as possible (ideahacks.la/registration). This is mainly because the registration and the login page should have the same design, and we'll work on redesigning them later (or wait until the design team gives us mockups)
DUE DATE: Would Aug 19 be ok? It's a little more than two weeks, and on a meeting day.—
